---  # https://docs.ansible.com/ansible/latest/collections/community/aws/iam_module.html
- name: Add AWS IAM user
  hosts: localhost
  tasks: 
  # Basic user creation example
  - name: Create two new IAM users with API keys
    community.aws.iam:
      iam_type: user
      name: "{{ item }}"
      state: present
      password: "3l6EUHxi2wL8XNR$$OUdJYES@wL#Fi6hCokl6IployJrJyRC7e"
      access_key_state: create
    loop:
    - jcleese
    - mpython