--- # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/lineinfile_module.html
- name: Manage file content
  hosts: amazon
  connection: ssh
  user: ec2-user
  become: true
  become_method: sudo 
  tasks: 
  - name: Add a line to a file if the file does not exist, without passing regexp
    ansible.builtin.lineinfile:
      path: /tmp/testfile
      line: 192.168.1.99 foo.lab.net foo
      create: yes


  - name: Ensure testfile content is changed
    ansible.builtin.lineinfile:
      path: /tmp/testfile
      regexp: '^192.168.1.99'
      line: 172.16.1.99 foo.lab.net foo

  - name: Ensure SELinux is set to enforcing mode
    ansible.builtin.lineinfile:
      path: /etc/selinux/config
      regexp: '^SELINUX='
      line: SELINUX=permissive